name: bearound_flutter_sdk
description: "Bearound Flutter SDK - Beacon detection and proximity tracking"
version: 2.3.5
repository: https://github.com/Bearound/bearound-flutter-sdk
issue_tracker: https://github.com/Bearound/bearound-flutter-sdk/issues
homepage:
topics: [bluetooth, beacons, proximity, background, location]

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ">=12.0.0 <13.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.6.1
  build_runner: ^2.4.0
  faker: ^2.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.bearound_flutter_sdk
        pluginClass: BearoundFlutterSdkPlugin
      ios:
        pluginClass: BearoundFlutterSdkPlugin
