name: bearound_flutter_sdk
description: "Bearound Flutter SDK"
version: 1.2.1
repository: https://github.com/Bearound/bearound-flutter-sdk
issue_tracker: https://github.com/Bearound/bearound-flutter-sdk/issues
homepage:
topics: [bluetooth, beacons, proximity, background, location]

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  permission_handler: ">=12.0.0 <13.0.0"
  location: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.bearound_flutter_sdk
        pluginClass: BearoundFlutterSdkPlugin
      ios:
        pluginClass: BearoundFlutterSdkPlugin